export const IconTypes = {
    Skype: 'skype',
    Phone: 'phone',
    Linkedin: 'linkedin',
    Envelope: 'envelope',  
    Plus: 'plus',  
    Search: 'search',
    CircleO: 'circle-o',
    SmileO: 'smile-o', 
    FrownO: 'frown-o',
    Pencil: 'pencil',
    Sun: 'sun-o',
    Moon: 'moon-o',
    User: 'user',
    SignOut: 'sign-out',
    Circle: 'circle',
    
    Spinner: 'spinner',
    Star: 'star',
};